name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: tukayev.it.com
          username: tukabpyj
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAembatW3
8ZO91BYPFi7Vo/AAAAEAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQC/jljDEdBI
1hUazx7bpuszYHSeHNNekUL2dOt0jRdNPAmEzt/BfbhXWC3Yn04eG0Fvd71p15+1MQDGz/
aQM/ZtD5iFph13e8Xx1QjpDDzXt8Uq6Fk+nlowf1J5bATYKPyRG1GuLHnQR4X/KVc3ASex
1R3yXIDG9L7L4cre2/5ZmftubBHl89p37x5j8MnT6kYW1DWgGiMnrxBijjStV6L/hm892T
RWmq/aL2EaO9pRFyn+FQtIUNRa6Wnbmp1lSbSr7ygxgrvjmSd7LE8GuqfyNgN66dMHhGa4
LvJkn2EyhDp+tLXhARRJ10j9/cXpcrD0VNUI28VdTywVhHbFNdurAAADwMCXXl4b0xeyAZ
UZB5zb8AGTbWJIQo5ud6ippVbPxETemOPxyAljlFAQd8W4WtD4FkAFxD5BME6zbIWTPZXg
yhDvhSlMOMOYMGIkGEhX+x2oKOHJSQH3hzefFA4VA+S3SvpgHikm+gzUX2ezDZpd8icGax
DlNqswYXiYhKj7VPdV+DJzECGadu9JK5tpPmrrIdZ3crBwIqGVNeOSxBi5uLjtxZnVTKSU
/LQOwqs1WyJJUf7l+Td4J2gFEPeOHyFXP2kbL32fmT5B61/Z9F31Q+W6ibkhlOXPoe+z+B
6M7sy3B+qhDTW5CALV7u2t3XjciRRMyHcgwBi78LdMH+Bmqo6KcKHMrMCLW3goWFrRbtvM
qfxJM8PvXVjt4yIpWdUHzLXtUiLCpH/5ctMPS+b+SEDKDuqY4ywprh/ivGL0oavw8qbphj
UYiqhYq/dP+sCL652B6+6iCRT/idnCZV6r8UYnSj5huV1mltAXOxqQWAT4kiMRqOBq4zhl
mycDTJi4XiAk/MZAWoRuanUf3K8LcK5DB+IJZQBMFD9/9pA2QvWySPydHfiBeAuVPhfVdQ
iyyHjL7oh9U2EEQX2B6S1KpJqLx7sbMBlhlEXRZ5aBjXzaZteUCNWXgZ8v/T3n8lFQRFkf
v2D6WRXM8k8m3MU4ZYpcNPec0SH34ufJa/Q5ORDpNEoHbxNAfz/WSXOd629lFm49i+PnPz
RUckFoO9W8tpRYm/S1c/LRzfU1RVWkfbUuxjEeSHdnbqgnbzumhLMqkVrcmx9rk9epe7OG
sAmjoTn6BOlO6v5zJvde0zwlup4UrbnFlm3dbiPuIL5+cKofS7g74F3zPEmW765OrZZMC5
PNxxZ0bnUzlEFdWibmSUpZTivBcg1jgUAeH5Rdksl94GIGrBilrU7VMvXNmbFCCz0CbmWZ
Q90i/JSO0tcwByaT8kLeXNJv4WGeF71CRsPGTrl71Pk5F8gcAeiR4mxUQA7qvKDJlvChVb
EfDbdSfMr4qLntS5WRq9dZFMoNK72ICvhDFiAf/ejGWVeuZsVb4QGzpm6D9jhsYRt5yJog
Af7TRZnbceTnRgipyrIK7q3yutgRZYHc9DCFUSHLApzBnqmIpG8mUn+3HhUtTD3g/mhTza
lyynOnS4vlVJCw18cfnOJ9tOlQLQdrSd3HhAGuvGadXAsjHHa+9jj9ET8+eQQxAqK2ibOP
K/FB6ZHHWh4IlQwDZYOD4IlTGXqxNEXpYoiBN6tAKoD1Pk97X0cZJR8wCuSrRoQoP7N2IX
ocvBUZ5g==
-----END OPENSSH PRIVATE KEY-----
          port: 21098
          script: |
            cd /home/tukabpyj/repositories/3droof
            git pull origin main
            npm install --production
            mkdir -p tmp
            touch tmp/restart.txt
